language: c

os: linux

env:
      - TEST="CppCheck"
      - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
      - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
      - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
      - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
dist: trusty
sudo: true
compiler:
      - gcc
      - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang-3.7
      - valgrind
      - cppcheck
before install:
  - sudo apt update
  - sudo apt install valgrind
  - sudo apt install cmake
  - sudo apt install cppcheck
script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - dir
     - ls
     - cppcheck --error-exitcode=1 --enable=warning,performance,information,style *.cpp *.h
     - cmake -DENABLE_CPPCHECK=ON -DCMAKE_CXX_COMPILER="g++-6" CMakeLists.txt
     - ls
     - make testStack
