language: c

os: linux

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
dist: xenial
sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - valgrind
      - cppcheck
      - cmake
matrix:
  include:
    - compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"

    - compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
before install:
  - eval "${MATRIX_EVAL}"
  - sudo apt update
install:
  ############################################################################
  # Install a recent CMake
  ############################################################################
  - cmake --version
  - gcc --version
  - clang --version
  - sudo apt install cppcheck
  - sudo apt install valgrind
  - sudo apt install libgtest-dev
  - cd /usr/src/gtest
  - dir
  - sudo cmake CMakeLists.txt || (cat CMakeFiles/CMakeError.log && CMakeFiles/CMakeOutput.log)
  - sudo make
  - sudo mv libgtest* /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"
script:
  ############################################################################
  # Build main and tests
  ############################################################################
  - cmake --version
  - dir
  - ls
  - sudo cmake -DCMAKE_VERBOSE_MAKEFILE=ON CMakeLists.txt
  - cppcheck --check-config --error-exitcode=1 --enable=warning,performance,information,style *c *.cpp *.h
  - ls
  - make
  - valgrind --leak-check=full -q ./Googletests/testArea
